/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminTeacherRouteRouteImport } from './routes/admin-teacher/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTeacherIndexRouteImport } from './routes/admin-teacher/index'
import { Route as AdminStudentIndexRouteImport } from './routes/admin-student/index'
import { Route as AdminTeacherStudyRouteImport } from './routes/admin-teacher/study'
import { Route as AdminTeacherStudentsRouteImport } from './routes/admin-teacher/students'
import { Route as AdminTeacherSettingsRouteImport } from './routes/admin-teacher/settings'
import { Route as AdminTeacherNotesRouteImport } from './routes/admin-teacher/notes'
import { Route as AdminTeacherHomeRouteImport } from './routes/admin-teacher/home'
import { Route as AdminTeacherChatRouteImport } from './routes/admin-teacher/chat'
import { Route as AdminStudentTopicTopicIdRouteImport } from './routes/admin-student/topic/$topicId'
import { Route as AdminStudentClassClassIdRouteImport } from './routes/admin-student/class/$classId'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api.trpc.$'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeacherRouteRoute = AdminTeacherRouteRouteImport.update({
  id: '/admin-teacher',
  path: '/admin-teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeacherIndexRoute = AdminTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTeacherRouteRoute,
} as any)
const AdminStudentIndexRoute = AdminStudentIndexRouteImport.update({
  id: '/admin-student/',
  path: '/admin-student/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeacherStudyRoute = AdminTeacherStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AdminTeacherRouteRoute,
} as any)
const AdminTeacherStudentsRoute = AdminTeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminTeacherRouteRoute,
} as any)
const AdminTeacherSettingsRoute = AdminTeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminTeacherRouteRoute,
} as any)
const AdminTeacherNotesRoute = AdminTeacherNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminTeacherRouteRoute,
} as any)
const AdminTeacherHomeRoute = AdminTeacherHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminTeacherRouteRoute,
} as any)
const AdminTeacherChatRoute = AdminTeacherChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminTeacherRouteRoute,
} as any)
const AdminStudentTopicTopicIdRoute =
  AdminStudentTopicTopicIdRouteImport.update({
    id: '/admin-student/topic/$topicId',
    path: '/admin-student/topic/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminStudentClassClassIdRoute =
  AdminStudentClassClassIdRouteImport.update({
    id: '/admin-student/class/$classId',
    path: '/admin-student/class/$classId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-teacher': typeof AdminTeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin-teacher/chat': typeof AdminTeacherChatRoute
  '/admin-teacher/home': typeof AdminTeacherHomeRoute
  '/admin-teacher/notes': typeof AdminTeacherNotesRoute
  '/admin-teacher/settings': typeof AdminTeacherSettingsRoute
  '/admin-teacher/students': typeof AdminTeacherStudentsRoute
  '/admin-teacher/study': typeof AdminTeacherStudyRoute
  '/admin-student': typeof AdminStudentIndexRoute
  '/admin-teacher/': typeof AdminTeacherIndexRoute
  '/admin-student/class/$classId': typeof AdminStudentClassClassIdRoute
  '/admin-student/topic/$topicId': typeof AdminStudentTopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-teacher/chat': typeof AdminTeacherChatRoute
  '/admin-teacher/home': typeof AdminTeacherHomeRoute
  '/admin-teacher/notes': typeof AdminTeacherNotesRoute
  '/admin-teacher/settings': typeof AdminTeacherSettingsRoute
  '/admin-teacher/students': typeof AdminTeacherStudentsRoute
  '/admin-teacher/study': typeof AdminTeacherStudyRoute
  '/admin-student': typeof AdminStudentIndexRoute
  '/admin-teacher': typeof AdminTeacherIndexRoute
  '/admin-student/class/$classId': typeof AdminStudentClassClassIdRoute
  '/admin-student/topic/$topicId': typeof AdminStudentTopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-teacher': typeof AdminTeacherRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin-teacher/chat': typeof AdminTeacherChatRoute
  '/admin-teacher/home': typeof AdminTeacherHomeRoute
  '/admin-teacher/notes': typeof AdminTeacherNotesRoute
  '/admin-teacher/settings': typeof AdminTeacherSettingsRoute
  '/admin-teacher/students': typeof AdminTeacherStudentsRoute
  '/admin-teacher/study': typeof AdminTeacherStudyRoute
  '/admin-student/': typeof AdminStudentIndexRoute
  '/admin-teacher/': typeof AdminTeacherIndexRoute
  '/admin-student/class/$classId': typeof AdminStudentClassClassIdRoute
  '/admin-student/topic/$topicId': typeof AdminStudentTopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-teacher'
    | '/login'
    | '/admin-teacher/chat'
    | '/admin-teacher/home'
    | '/admin-teacher/notes'
    | '/admin-teacher/settings'
    | '/admin-teacher/students'
    | '/admin-teacher/study'
    | '/admin-student'
    | '/admin-teacher/'
    | '/admin-student/class/$classId'
    | '/admin-student/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-teacher/chat'
    | '/admin-teacher/home'
    | '/admin-teacher/notes'
    | '/admin-teacher/settings'
    | '/admin-teacher/students'
    | '/admin-teacher/study'
    | '/admin-student'
    | '/admin-teacher'
    | '/admin-student/class/$classId'
    | '/admin-student/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/admin-teacher'
    | '/login'
    | '/admin-teacher/chat'
    | '/admin-teacher/home'
    | '/admin-teacher/notes'
    | '/admin-teacher/settings'
    | '/admin-teacher/students'
    | '/admin-teacher/study'
    | '/admin-student/'
    | '/admin-teacher/'
    | '/admin-student/class/$classId'
    | '/admin-student/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminTeacherRouteRoute: typeof AdminTeacherRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminStudentIndexRoute: typeof AdminStudentIndexRoute
  AdminStudentClassClassIdRoute: typeof AdminStudentClassClassIdRoute
  AdminStudentTopicTopicIdRoute: typeof AdminStudentTopicTopicIdRoute
}
export interface FileServerRoutesByFullPath {
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/trpc/$'
  id: '__root__' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-teacher': {
      id: '/admin-teacher'
      path: '/admin-teacher'
      fullPath: '/admin-teacher'
      preLoaderRoute: typeof AdminTeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-teacher/': {
      id: '/admin-teacher/'
      path: '/'
      fullPath: '/admin-teacher/'
      preLoaderRoute: typeof AdminTeacherIndexRouteImport
      parentRoute: typeof AdminTeacherRouteRoute
    }
    '/admin-student/': {
      id: '/admin-student/'
      path: '/admin-student'
      fullPath: '/admin-student'
      preLoaderRoute: typeof AdminStudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-teacher/study': {
      id: '/admin-teacher/study'
      path: '/study'
      fullPath: '/admin-teacher/study'
      preLoaderRoute: typeof AdminTeacherStudyRouteImport
      parentRoute: typeof AdminTeacherRouteRoute
    }
    '/admin-teacher/students': {
      id: '/admin-teacher/students'
      path: '/students'
      fullPath: '/admin-teacher/students'
      preLoaderRoute: typeof AdminTeacherStudentsRouteImport
      parentRoute: typeof AdminTeacherRouteRoute
    }
    '/admin-teacher/settings': {
      id: '/admin-teacher/settings'
      path: '/settings'
      fullPath: '/admin-teacher/settings'
      preLoaderRoute: typeof AdminTeacherSettingsRouteImport
      parentRoute: typeof AdminTeacherRouteRoute
    }
    '/admin-teacher/notes': {
      id: '/admin-teacher/notes'
      path: '/notes'
      fullPath: '/admin-teacher/notes'
      preLoaderRoute: typeof AdminTeacherNotesRouteImport
      parentRoute: typeof AdminTeacherRouteRoute
    }
    '/admin-teacher/home': {
      id: '/admin-teacher/home'
      path: '/home'
      fullPath: '/admin-teacher/home'
      preLoaderRoute: typeof AdminTeacherHomeRouteImport
      parentRoute: typeof AdminTeacherRouteRoute
    }
    '/admin-teacher/chat': {
      id: '/admin-teacher/chat'
      path: '/chat'
      fullPath: '/admin-teacher/chat'
      preLoaderRoute: typeof AdminTeacherChatRouteImport
      parentRoute: typeof AdminTeacherRouteRoute
    }
    '/admin-student/topic/$topicId': {
      id: '/admin-student/topic/$topicId'
      path: '/admin-student/topic/$topicId'
      fullPath: '/admin-student/topic/$topicId'
      preLoaderRoute: typeof AdminStudentTopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-student/class/$classId': {
      id: '/admin-student/class/$classId'
      path: '/admin-student/class/$classId'
      fullPath: '/admin-student/class/$classId'
      preLoaderRoute: typeof AdminStudentClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminTeacherRouteRouteChildren {
  AdminTeacherChatRoute: typeof AdminTeacherChatRoute
  AdminTeacherHomeRoute: typeof AdminTeacherHomeRoute
  AdminTeacherNotesRoute: typeof AdminTeacherNotesRoute
  AdminTeacherSettingsRoute: typeof AdminTeacherSettingsRoute
  AdminTeacherStudentsRoute: typeof AdminTeacherStudentsRoute
  AdminTeacherStudyRoute: typeof AdminTeacherStudyRoute
  AdminTeacherIndexRoute: typeof AdminTeacherIndexRoute
}

const AdminTeacherRouteRouteChildren: AdminTeacherRouteRouteChildren = {
  AdminTeacherChatRoute: AdminTeacherChatRoute,
  AdminTeacherHomeRoute: AdminTeacherHomeRoute,
  AdminTeacherNotesRoute: AdminTeacherNotesRoute,
  AdminTeacherSettingsRoute: AdminTeacherSettingsRoute,
  AdminTeacherStudentsRoute: AdminTeacherStudentsRoute,
  AdminTeacherStudyRoute: AdminTeacherStudyRoute,
  AdminTeacherIndexRoute: AdminTeacherIndexRoute,
}

const AdminTeacherRouteRouteWithChildren =
  AdminTeacherRouteRoute._addFileChildren(AdminTeacherRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminTeacherRouteRoute: AdminTeacherRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminStudentIndexRoute: AdminStudentIndexRoute,
  AdminStudentClassClassIdRoute: AdminStudentClassClassIdRoute,
  AdminStudentTopicTopicIdRoute: AdminStudentTopicTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
